// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfdnyaivesyiofwesqhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZG55YWl2ZXN5aW9md2VzcWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzEwNzIsImV4cCI6MjA3NDEwNzA3Mn0.5Sdu7zms9d7oATO2hM4pB9TWTyNRq7vySh9P2l0yIrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});